server:
  port: 8763
  servlet:
    context-path: /message
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: message
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
  mail:
    host: smtp.163.com
    username: yushengjun2018@163.com
    password: itmayiedu644
    default-encoding: utf-8

########################################

msg:
  subject: lye的电子商务平台，会员注册成功邮件。
  text:  恭喜您的账户{},注册成功!